"""Korean → official English university names, with campus-suffix handling."""
from __future__ import annotations

import re

EN = {
    "가야대학교": "Kaya University",
    "가천대학교": "Gachon University",
    "가톨릭관동대학교": "Catholic Kwandong University",
    "가톨릭꽃동네대학교": "Kkottongnae University",
    "가톨릭대학교": "Catholic University of Korea",
    "감리교신학대학교": "Methodist Theological University",
    "강남대학교": "Kangnam University",
    "강서대학교": "Kangseo University",
    "강원대학교": "Kangwon National University",
    "건국대학교": "Konkuk University",
    "건양대학교": "Konyang University",
    "건양사이버대학교": "Konyang Cyber University",
    "경기대학교": "Kyonggi University",
    "경남대학교": "Kyungnam University",
    "경동대학교": "Kyungdong University",
    "경북대학교": "Kyungpook National University",
    "경상국립대학교": "Gyeongsang National University",
    "경성대학교": "Kyungsung University",
    "경운대학교": "Kyungwoon University",
    "경인교육대학교": "Gyeongin National University of Education",
    "경일대학교": "Kyungil University",
    "경희대학교": "Kyung Hee University",
    "경희사이버대학교": "Kyung Hee Cyber University",
    "계명대학교": "Keimyung University",
    "고려대학교": "Korea University",
    "고려사이버대학교": "Korea Cyber University",
    "고신대학교": "Kosin University",
    "광신대학교": "Kwangshin University",
    "광운대학교": "Kwangwoon University",
    "광주가톨릭대학교": "Gwangju Catholic University",
    "광주과학기술원": "Gwangju Institute of Science and Technology (GIST)",
    "광주대학교": "Gwangju University",
    "광주여자대학교": "Kwangju Women's University",
    "국립강릉원주대학교": "Gangneung-Wonju National University",
    "국립경국대학교": "Gyeongguk National University",
    "국립공주대학교": "Kongju National University",
    "국립군산대학교": "Kunsan National University",
    "국립금오공과대학교": "Kumoh National Institute of Technology",
    "국립목포대학교": "Mokpo National University",
    "국립목포해양대학교": "Mokpo National Maritime University",
    "국립부경대학교": "Pukyong National University",
    "국립순천대학교": "Sunchon National University",
    "국립창원대학교": "Changwon National University",
    "국립한국교통대학교": "Korea National University of Transportation",
    "국립한국해양대학교": "Korea Maritime and Ocean University",
    "국립한밭대학교": "Hanbat National University",
    "국민대학교": "Kookmin University",
    "국제사이버대학교": "International Cyber University",
    "극동대학교": "Far East University",
    "글로벌사이버대학교": "Global Cyber University",
    "김천대학교": "Gimcheon University",
    "나사렛대학교": "Korea Nazarene University",
    "남부대학교": "Nambu University",
    "남서울대학교": "Namseoul University",
    "단국대학교": "Dankook University",
    "대구가톨릭대학교": "Daegu Catholic University",
    "대구경북과학기술원": "Daegu Gyeongbuk Institute of Science and Technology (DGIST)",
    "대구교육대학교": "Daegu National University of Education",
    "대구대학교": "Daegu University",
    "대구사이버대학교": "Daegu Cyber University",
    "대구예술대학교": "Daegu Arts University",
    "대구한의대학교": "Daegu Haany University",
    "대신대학교": "Daeshin University",
    "대전가톨릭대학교": "Daejeon Catholic University",
    "대전대학교": "Daejeon University",
    "대진대학교": "Daejin University",
    "덕성여자대학교": "Duksung Women's University",
    "동국대학교": "Dongguk University",
    "동덕여자대학교": "Dongduk Women's University",
    "동명대학교": "Tongmyong University",
    "동서대학교": "Dongseo University",
    "동신대학교": "Dongshin University",
    "동아대학교": "Dong-A University",
    "동양대학교": "Dongyang University",
    "동의대학교": "Dong-eui University",
    "디지털서울문화예술대학교": "Digital Seoul Culture Arts University",
    "명지대학교": "Myongji University",
    "목원대학교": "Mokwon University",
    "배재대학교": "Pai Chai University",
    "백석대학교": "Baekseok University",
    "부산가톨릭대학교": "Catholic University of Pusan",
    "부산대학교": "Pusan National University",
    "부산디지털대학교": "Busan Digital University",
    "부산외국어대학교": "Busan University of Foreign Studies",
    "사이버한국외국어대학교": "Cyber Hankuk University of Foreign Studies",
    "삼육대학교": "Sahmyook University",
    "상명대학교": "Sangmyung University",
    "상지대학교": "Sangji University",
    "서강대학교": "Sogang University",
    "서경대학교": "Seokyeong University",
    "서울과학기술대학교": "Seoul National University of Science and Technology",
    "서울교육대학교": "Seoul National University of Education",
    "서울기독대학교": "Seoul Christian University",
    "서울대학교": "Seoul National University",
    "서울디지털대학교": "Seoul Digital University",
    "서울사이버대학교": "Seoul Cyber University",
    "서울시립대학교": "University of Seoul",
    "서울신학대학교": "Seoul Theological University",
    "서울여자대학교": "Seoul Women's University",
    "서울장신대학교": "Seoul Jangsin University",
    "서울한영대학교": "Seoul Hanyoung University",
    "서원대학교": "Seowon University",
    "선문대학교": "Sun Moon University",
    "성결대학교": "Sungkyul University",
    "성공회대학교": "Sungkonghoe University",
    "성균관대학교": "Sungkyunkwan University",
    "성신여자대학교": "Sungshin Women's University",
    "세명대학교": "Semyung University",
    "세종대학교": "Sejong University",
    "세종사이버대학교": "Sejong Cyber University",
    "세한대학교": "Sehan University",
    "송원대학교": "Songwon University",
    "수원가톨릭대학교": "Suwon Catholic University",
    "수원대학교": "University of Suwon",
    "숙명여자대학교": "Sookmyung Women's University",
    "순천향대학교": "Soonchunhyang University",
    "숭실대학교": "Soongsil University",
    "숭실사이버대학교": "Soongsil Cyber University",
    "신경주대학교": "Shin Gyeongju University",
    "신라대학교": "Silla University",
    "신한대학교": "Shinhan University",
    "아신대학교": "ACTS University",
    "아주대학교": "Ajou University",
    "안양대학교": "Anyang University",
    "연세대학교": "Yonsei University",
    "영남대학교": "Yeungnam University",
    "영남신학대학교": "Yeungnam Theological University",
    "영산대학교": "Youngsan University",
    "영산선학대학교": "Youngsan University of Seon Studies",
    "예원예술대학교": "Yewon Arts University",
    "용인대학교": "Yong In University",
    "우석대학교": "Woosuk University",
    "우송대학교": "Woosong University",
    "울산과학기술원": "Ulsan National Institute of Science and Technology (UNIST)",
    "울산대학교": "University of Ulsan",
    "원광대학교": "Wonkwang University",
    "원광디지털대학교": "Wonkwang Digital University",
    "위덕대학교": "Uiduk University",
    "유원대학교": "U1 University",
    "을지대학교": "Eulji University",
    "이화여자대학교": "Ewha Womans University",
    "인제대학교": "Inje University",
    "인천가톨릭대학교": "Incheon Catholic University",
    "인천대학교": "Incheon National University",
    "인하대학교": "Inha University",
    "장로회신학대학교": "Presbyterian University and Theological Seminary",
    "전남대학교": "Chonnam National University",
    "전북대학교": "Jeonbuk National University",
    "전주대학교": "Jeonju University",
    "제주국제대학교": "Jeju International University",
    "제주대학교": "Jeju National University",
    "조선대학교": "Chosun University",
    "중부대학교": "Joongbu University",
    "중앙대학교": "Chung-Ang University",
    "중앙승가대학교": "Joong-Ang Sangha University",
    "중원대학교": "Jungwon University",
    "차의과학대학교": "CHA University",
    "창신대학교": "Changshin University",
    "청운대학교": "Chungwoon University",
    "청주대학교": "Cheongju University",
    "초당대학교": "Chodang University",
    "총신대학교": "Chongshin University",
    "추계예술대학교": "Chugye University for the Arts",
    "충남대학교": "Chungnam National University",
    "충북대학교": "Chungbuk National University",
    "칼빈대학교": "Calvin University",
    "태재대학교": "Taejae University",
    "평택대학교": "Pyeongtaek University",
    "포항공과대학교": "Pohang University of Science and Technology (POSTECH)",
    "한경국립대학교": "Hankyong National University",
    "한국공학대학교": "Tech University of Korea",
    "한국과학기술원": "Korea Advanced Institute of Science and Technology (KAIST)",
    "한국교원대학교": "Korea National University of Education",
    "한국기술교육대학교": "Korea University of Technology and Education",
    "한국방송통신대학교": "Korea National Open University",
    "한국성서대학교": "Korean Bible University",
    "한국열린사이버대학교": "Open Cyber University of Korea",
    "한국예술종합학교": "Korea National University of Arts",
    "한국외국어대학교": "Hankuk University of Foreign Studies",
    "한국전통문화대학교": "Korea National University of Cultural Heritage",
    "한국체육대학교": "Korea National Sport University",
    "한국침례신학대학교": "Korea Baptist Theological University",
    "한국항공대학교": "Korea Aerospace University",
    "한남대학교": "Hannam University",
    "한동대학교": "Handong Global University",
    "한라대학교": "Halla University",
    "한림대학교": "Hallym University",
    "한서대학교": "Hanseo University",
    "한성대학교": "Hansung University",
    "한세대학교": "Hansei University",
    "한신대학교": "Hanshin University",
    "한양대학교": "Hanyang University",
    "한양사이버대학교": "Hanyang Cyber University",
    "한일장신대학교": "Hanil University",
    "협성대학교": "Hyupsung University",
    "호남대학교": "Honam University",
    "호남신학대학교": "Honam Theological University and Seminary",
    "호서대학교": "Hoseo University",
    "호원대학교": "Howon University",
    "홍익대학교": "Hongik University",
    "화성의과학대학교": "Hwaseong University of Medical Science",
    "화신사이버대학교": "Hwashin Cyber University",
}

_CAMPUS = {"ERICA": "ERICA", "글로컬": "Glocal", "세종": "Sejong", "WISE": "WISE",
           "미래": "Mirae", "양산": "Yangsan", "해운대": "Haeundae", "김해": "Gimhae"}
_ORD = {"2": "2nd", "3": "3rd", "4": "4th"}


def to_english(name_ko: str) -> str:
    """Return the official English name (+ campus tag) for a Korean university name."""
    tag = None
    mp = re.search(r"\(([^)]+)\)", name_ko)
    if mp and mp.group(1) in _CAMPUS:
        tag = _CAMPUS[mp.group(1)]
    mc = re.search(r"제(\d)캠퍼스", name_ko)
    if mc:
        tag = f"{_ORD.get(mc.group(1), mc.group(1))} Campus"
    base = re.sub(r"\([^)]*\)", "", name_ko)
    base = re.sub(r"_.*$", "", base).strip()
    en = EN.get(base, base)
    return f"{en} ({tag})" if tag else en
